name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Install libssl1.1
        run: |
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
          sudo apt-get install -f -y

      - name: Install MongoDB
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
          sudo mkdir -p /data/db
          sudo chown -R mongodb:mongodb /data/db
          sudo systemctl start mongod
          sudo systemctl enable mongod

      - name: Verify MongoDB Installation
        run: |
          mongo --eval "db.runCommand({ connectionStatus: 1 })"

      - name: Run Test File
        run: node .github/workflows/loadTest.js

      - name: Start Server
        run: npm start &
        env:
          PORT: 8090

      - name: Wait for Server
        run: npx wait-on http://localhost:8090

      - name: Run Cypress Tests
        run: |
          npm run cypress:run:workflow || true

      - name: Run Index.js
        run: node .github/workflows/index.js
