name: Run Tests

on:
  push:
    branches:
      - master  # Trigger workflow on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger workflow on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Replace with your Node.js version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run Jest tests
      - name: Run Tests
        run: npm test
