name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use a stable Node.js version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Install MongoDB
      - name: Install MongoDB
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
          sudo systemctl start mongod
          sudo systemctl enable mongod

      # Step 5: Verify MongoDB Installation
      - name: Verify MongoDB Installation
        run: |
          mongo --eval "db.runCommand({ connectionStatus: 1 })"

      # Step 6: Run a test file
      - name: Run Test File
        run: node .github/workflows/loadTest.js

      # Step 7: Start the server
      - name: Start Server
        run: npm start &
        env:
          PORT: 8090

      # Step 8: Wait for the server to be ready
      - name: Wait for Server
        run: npx wait-on http://localhost:8090

      # Step 9: Run Cypress tests
      - name: Run Cypress Tests
        run: npm run cypress:run:workflow || true

      # Step 10: Run `index.js` Script
      - name: Run Index.js
        run: node .github/workflows/index.js
