name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use Node.js version compatible with your project

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Start the server
      - name: Start Server
        run: npm start &
        env:
          PORT: 8090 # Ensure the server runs on the correct port

      # Step 5: Wait for the server to be ready
      - name: Wait for Server
        run: npx wait-on http://localhost:8090

      # Step 6: Run Cypress tests
      - name: Run Cypress Tests
        run: npm run cypress:run:workflow

      # Step 7: Upload Test Results
      - name: Upload Cypress Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: .github/workflows/cypress/results

      # Step 8: Print Results
      - name: Print Cypress Results
        run: cat .github/workflows/cypress/results/*.json
